routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->guest()) {
        return redirect()->route('login');
    } else {
        return redirect()->route('event.index');
    }
});

Auth::routes();

Route::group(['prefix' => '/organizer', 'middleware' => ['auth']], function () {

    // Event
    Route::resource('/event', \App\Http\Controllers\EventController::class);

    // Channel
    Route::resource('/event/{event}/channel', \App\Http\Controllers\ChannelController::class);

    // Room
    Route::get('/event/{event}/room/capacity', [App\Http\Controllers\RoomController::class, 'capacity'])->name('room.capacity');
    Route::resource('/event/{event}/room', \App\Http\Controllers\RoomController::class);

    // Session
    Route::resource('/event/{event}/session', \App\Http\Controllers\SessionController::class);

    // Ticket
    Route::resource('/event/{event}/ticket', \App\Http\Controllers\TicketController::class);

});

resources/views/layouts/alert.blade.php
@if(session('message'))
<div class="alert alert-success">
    {{ session('message') }}
</div>
@elseif($errors->any())
<div class="alert alert-danger">
    {{ collect($errors->all())->join(', ') }}
</div>
@endif

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Event Backend</title>

    <base href="../">
    <!-- Bootstrap core CSS -->
    <link href="{{asset('assets/css/bootstrap.css')}}" rel="stylesheet">
    <!-- Custom styles -->
    <link href="{{asset('assets/css/custom.css')}}" rel="stylesheet">

    @yield('style')

</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{route('event.index')}}">Event Platform</a>
    <span class="navbar-organizer w-100">{{auth()->user()->name}}</span>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" id="logout" href="{{ route('logout') }}"
               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Sign out</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </li>
    </ul>
</nav>

@yield('content')

@yield('script')

</body>
</html>

resources/views/layouts/app_.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/combobox.blade.php
<label for="select-{{ $name }}">{{ $label }}</label>
<select class="form-control" id="select-{{ $name }}" name="{{ $name }}">

    @foreach($options as $key => $option)
        <option value="{{ $key }}" {{ $key == old($name) ? 'selected' : '' }}>{{ $option }}</option>
    @endforeach

</select>
@if($errors->first($name))
    <div class="invalid-feedback">
        {{ $errors->first($name) }}
    </div>
@endif

resources/views/layouts/sidebar1.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item"><a class="nav-link active" href="{{route('event.index')}}">Manage Events</a></li>
        </ul>
    </div>
</nav>

resources/views/layouts/sidebar2.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item"><a class="nav-link" href="{{route('event.index')}}">Manage Events</a></li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>{{$event->name}}</span>
        </h6>
        <ul class="nav flex-column">
            <li class="nav-item"><a class="nav-link active" href="{{route('event.show', $event)}}">Overview</a></li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Reports</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item"><a class="nav-link" href="{{route('room.capacity', $event)}}">Room capacity</a></li>
        </ul>

    </div>
</nav>

resources/views/layouts/sidebar3.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item"><a class="nav-link" href="{{route('event.index')}}">Manage Events</a></li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>{{$event->name}}</span>
        </h6>
        <ul class="nav flex-column">
            <li class="nav-item"><a class="nav-link" href="{{route('event.show', $event)}}">Overview</a></li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Reports</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item"><a class="nav-link active" href="{{route('room.capacity', $event)}}">Room capacity</a></li>
        </ul>

    </div>
</nav>

resources/views/layouts/textarea.blade.php
<label for="textarea-{{ $name }}">{{ $label }}</label>
<textarea class="form-control {{$errors->first($name) ? 'is-invalid' : ''}}" id="textarea-{{ $name }}" name="{{ $name }}" placeholder="" rows="5">{{ old($name) ? old($name) : (isset($fill) ? $fill : '') }}</textarea>
@if($errors->first($name))
    <div class="invalid-feedback">
        {{ $errors->first($name) }}
    </div>
@endif

resources/views/layouts/textfield.blade.php
<label for="input-{{$name}}">{{$label}}</label>
<input type="{{$type}}" class="form-control {{$errors->first($name) ? 'is-invalid' : ''}}" id="input-{{$name}}" name="{{$name}}" placeholder="{{isset($placeholder) ? $placeholder : ''}}" value="{{old($name) ? old($name) : (isset($fill) ? $fill : ($type == 'cost' ? '0' : '')) }}">

@if($errors->first($name))
<div class="invalid-feedback">
    {{$errors->first($name)}}
</div>
@endif