routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->guest()) {
        return redirect()->route('login');
    } else {
        return redirect()->route('event.index');
    }
});

Auth::routes();

Route::group(['prefix' => '/organizer', 'middleware' => ['auth']], function () {

    // Event
    Route::resource('/event', \App\Http\Controllers\EventController::class);

    // Channel
    Route::resource('/event/{event}/channel', \App\Http\Controllers\ChannelController::class);

    // Room
    Route::get('/event/{event}/room/capacity', [App\Http\Controllers\RoomController::class, 'capacity'])->name('room.capacity');
    Route::resource('/event/{event}/room', \App\Http\Controllers\RoomController::class);

    // Session
    Route::resource('/event/{event}/session', \App\Http\Controllers\SessionController::class);

    // Ticket
    Route::resource('/event/{event}/ticket', \App\Http\Controllers\TicketController::class);

});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;
    protected $guarded = [];
    public $timestamps = false;
    protected $hidden  = ['organizer_id'];

    public function organizer () {
        return $this->belongsTo(Organizer::class);
    }

    public function channels () {
        return $this->hasMany(Channel::class);
    }

    public function getRoomsAttribute () {
        return $this->channels->map(function($channel) {
            return $channel->rooms;
        })->flatten();
    }

    public function getSessionsAttribute () {
        return $this->rooms->map(function($room) {
            return $room->sessions;
        })->flatten();
    }

    public function tickets () {
        return $this->hasMany(EventTicket::class);
    }

    public function getDateDisplayAttribute () {
        return date('F j, Y', strtotime($this->date));
    }

}

app/Http/Controllers/API/EventController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Event;
use App\Models\Organizer;
use Illuminate\Http\Request;

class EventController extends Controller
{
    //
    function __construct (Event $event, Organizer $organizer) {
        $this->event     = $event;
        $this->organizer = $organizer;
    }

    public function index () {

        // Get all events order by their date asc
        $events = $this->event->orderBy('date', 'asc')->with(['organizer'])->get();

        // Return JSON
        return response()->json([
            'events' => $events,
        ], 200);

    }

    public function show ($organizer_slug, $event_slug) {

        $event = $this->event->where('slug', $event_slug)->with([
            'channels' => function ($channel) {
                $channel->with(['rooms' => function ($room) {
                    $room->with(['sessions'])->get();
                }])->get();
            }, 'tickets' ])->first();

        if (!$event) return response()->json(['message' => 'Event not found'], 404);

        $organizer = $this->organizer->where('slug', $organizer_slug)->first();
        if (!$organizer) return response()->json(['message' => 'Organizer not found'], 404);

        if ($event->organizer_id != $organizer->id) return response()->json(['message' => 'Event not found'], 404);

        // Return JSON
        return response()->json($event, 200);

    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use App\Models\Organizer;
use Illuminate\Http\Request;

class EventController extends Controller
{
    //
    function __construct (Event $event, Organizer $organizer) {
        $this->event     = $event;
        $this->organizer = $organizer;
    }

    public function index () {
        // Define Organizer
        $organizer = auth()->user();

        // Get all events by organizer
        $events = $this->event->where('organizer_id', $organizer->id)->get();

        // Return view
        return view('event.index', compact('events'));
    }

    public function show (Event $event) {
        // Define Organizer
        $organizer = auth()->user();

        // Handle event
        if ($organizer->id != $event->organizer_id) abort(403);

        // Return view
        return view('event.show', compact('event'));
    }

    public function create () {
        // Return view
        return view('event.create');
    }

    public function store (Request $request) {

        // Validation
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required|regex:/^[a-z0-9-]+$/|unique:events,slug',
            'date' => 'required',
        ]);

        // Store
        $event = $this->event->create([
            'name'         => $request->name,
            'slug'         => $request->slug,
            'date'         => $request->date,
            'organizer_id' => auth()->user()->id,
        ]);

        // Return redirect
        return redirect()->route('event.show', $event)->with('message', 'Event successfully created');
    }

    public function edit (Event $event) {

        // Define Organizer
        $organizer = auth()->user();

        // Handle event
        if ($organizer->id != $event->organizer_id) abort(403);

        // Return view
        return view('event.edit', compact('event'));
    }

    public function update (Event $event, Request $request) {
        // Define Organizer
        $organizer = auth()->user();

        // Handle event
        if ($organizer->id != $event->organizer_id) abort(403);

        // Validation
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required|regex:/^[a-z0-9-]+$/|unique:events,slug,' . $event->id,
            'date' => 'required',
        ]);

        // Update
        $event->update([
            'name'         => $request->name,
            'slug'         => $request->slug,
            'date'         => $request->date,
        ]);

        // Return redirect
        return redirect()->route('event.show', $event)->with('message', 'Event successfully updated');
    }

}

resources/views/event/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @include('layouts.sidebar1')

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Manage Events</h1>
                </div>

                <div class="mb-3 pt-3 pb-2">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h2 class="h4">Create new event</h2>
                    </div>
                </div>

                <form class="needs-validation" novalidate action="{{route('event.store')}}" method="POST">

                    @csrf

                    <div class="row">
                        <div class="col-12 col-lg-4 mb-3">
                            @include('layouts.textfield', [
                                'label' => 'Name',
                                'name'  => 'name',
                                'type'  => 'text',
                            ])
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-lg-4 mb-3">
                            @include('layouts.textfield', [
                                'label' => 'Slug',
                                'name'  => 'slug',
                                'type'  => 'text',
                            ])
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-lg-4 mb-3">
                            @include('layouts.textfield', [
                                'label' => 'Date',
                                'name'  => 'date',
                                'type'  => 'date',
                            ])
                        </div>
                    </div>

                    <hr class="mb-4">
                    <button class="btn btn-primary" type="submit">Save event</button>
                    <a href="{{route('event.index')}}" class="btn btn-link">Cancel</a>
                </form>

            </main>
        </div>
    </div>
@endsection

resources/views/event/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @include('layouts.sidebar2')

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="border-bottom mb-3 pt-3 pb-2 event-title">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h1 class="h2">{{$event->name}}</h1>
                    </div>
                    <span class="h6">{{$event->display_date}}</span>
                </div>

                <div class="mb-3 pt-3 pb-2">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h2 class="h4">Edit event</h2>
                    </div>
                </div>

                <form class="needs-validation" novalidate action="{{route('event.update', $event)}}" method="POST">

                    @csrf
                    @method('PUT')

                    <div class="row">
                        <div class="col-12 col-lg-4 mb-3">
                            @include('layouts.textfield', [
                                'label' => 'Name',
                                'name'  => 'name',
                                'type'  => 'text',
                                'fill'  => $event->name,
                            ])
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-lg-4 mb-3">
                            @include('layouts.textfield', [
                                'label' => 'Slug',
                                'name'  => 'slug',
                                'type'  => 'text',
                                'fill'  => $event->slug,
                            ])
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 col-lg-4 mb-3">
                            @include('layouts.textfield', [
                                'label' => 'Date',
                                'name'  => 'date',
                                'type'  => 'date',
                                'fill'  => $event->date,
                            ])
                        </div>
                    </div>

                    <hr class="mb-4">
                    <button class="btn btn-primary" type="submit">Save event</button>
                    <a href="{{route('event.show', $event)}}" class="btn btn-link">Cancel</a>
                </form>

            </main>
        </div>
    </div>
@endsection

resources/views/event/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @include('layouts.sidebar1')

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Manage Events</h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group mr-2">
                            <a href="{{route('event.create')}}" class="btn btn-sm btn-outline-secondary">Create new event</a>
                        </div>
                    </div>
                </div>

                <div class="row events">

                    @foreach($events as $event)
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <a href="{{route('event.show', $event)}}" class="btn text-left event">
                                <div class="card-body">
                                    <h5 class="card-title">{{$event->name}}</h5>
                                    <p class="card-subtitle">{{$event->date_display}}</p>
                                    <hr>
                                    <p class="card-text">{{number_format($event->sessions->count(), 0)}} registrations</p>
                                </div>
                            </a>
                        </div>
                    </div>
                    @endforeach

                </div>

            </main>
        </div>
    </div>
@endsection

resources/views/event/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @include('layouts.sidebar2')

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="border-bottom mb-3 pt-3 pb-2 event-title">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h1 class="h2">{{$event->name}}</h1>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <a href="{{route('event.edit', $event)}}" class="btn btn-sm btn-outline-secondary">Edit event</a>
                            </div>
                        </div>
                    </div>
                    <span class="h6">{{$event->display_date}}</span>
                </div>

                @include('layouts.alert')

                <!-- Tickets -->
                <div id="tickets" class="mb-3 pt-3 pb-2">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h2 class="h4">Tickets</h2>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <a href="{{route('ticket.create', $event)}}" class="btn btn-sm btn-outline-secondary">
                                    Create new ticket
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row tickets">
                    @foreach($event->tickets as $ticket)
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title">{{$ticket->name}}</h5>
                                    <p class="card-text">{{$ticket->cost ? $ticket->cost : 0}}.-</p>
                                    <p class="card-text">{!! $ticket->description ? $ticket->description : '&nbsp;' !!}</p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>

                <!-- Sessions -->
                <div id="sessions" class="mb-3 pt-3 pb-2">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h2 class="h4">Sessions</h2>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <a href="{{route('session.create', $event)}}" class="btn btn-sm btn-outline-secondary">
                                    Create new session
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="table-responsive sessions">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Time</th>
                            <th>Type</th>
                            <th class="w-100">Title</th>
                            <th>Speaker</th>
                            <th>Channel</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($event->sessions as $session)
                            <tr>
                                <td class="text-nowrap">{{ date('H:i', strtotime($session->start)) }} - {{ date('H:i', strtotime($session->end)) }}</td>
                                <td>{{$session->type}}</td>
                                <td><a href="{{route('session.edit', [$event, $session])}}">{{$session->title}}</a></td>
                                <td class="text-nowrap">{{$session->speaker}}</td>
                                <td class="text-nowrap">{{$session->room->channel->name}} / {{$session->room->name}}</td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>

                <!-- Channels -->
                <div id="channels" class="mb-3 pt-3 pb-2">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h2 class="h4">Channels</h2>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <a href="{{route('channel.create', $event)}}" class="btn btn-sm btn-outline-secondary">
                                    Create new channel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row channels">
                    @foreach($event->channels as $channel)
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title">{{$channel->name}}</h5>
                                    <p class="card-text">{{$channel->sessions->count()}} sessions, {{$channel->rooms->count()}} room</p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>

                <!-- Rooms -->
                <div id="rooms" class="mb-3 pt-3 pb-2">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center">
                        <h2 class="h4">Rooms</h2>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <a href="{{route('room.create', $event)}}" class="btn btn-sm btn-outline-secondary">
                                    Create new room
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="table-responsive rooms">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Capacity</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($event->rooms as $room)
                            <tr>
                                <td>{{$room->name}}</td>
                                <td>{{number_format($room->capacity, 0)}}</td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>

            </main>
        </div>
    </div>
@endsection